# Generated by Django 4.1.7 on 2023-06-19 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningcurveapp', '0003_chaptercompletion_courserate_studentquiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_course', to='learningcurveapp.course'),
        ),
    ]
