# Generated by Django 3.2.18 on 2023-06-21 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningcurveapp', '0004_author_facebook_link_author_instagram_link_and_more'),
        ('learningcurveapp', '0005_author_facebook_link_author_instagram_link_and_more'),
    ]

    operations = [
    ]
